[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
shared = { version = "0.1.0", path = "../shared" }
