[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { workspace = true }
tokio = { version = "1.40.0", default-features = true, features = ["full"] }
log = { workspace = true }
env_logger = { workspace = true }
chrono = { workspace = true }
colored = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
shared = { path = "../shared" }
rand = "0.8.5"
