[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
log = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
tokio = "1.40.0"
derive-getters = { workspace = true }
