[package]
name = "gfx"
version = "0.1.0"
authors = ["Obito-git <antonmyroshnychenko@gmail.com>"]
edition = "2021"

[dependencies]
dioxus = { version = "0.5", features = ["web"] }
dioxus-logger = "0.5.1"
shared = { path = "../shared" }
